name: Prevent Merging

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  do-not-merge:
    if: ${{ (contains(github.event.*.labels.*.name, 'draft') || contains(github.event.*.labels.*.name, 'Work in Progress')) && needs.test-api.result == 'success' }}
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "Pull request is labeled as 'Work in Progress' or 'Draft' "
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1
